FORMAT: 1A
HOST: https://api.codecorps.org

# API Reference

The Code Corps API is a [JSON API](https://github.com/code-corps/code-corps-api)-based REST API built on Rails. You can visit the [API project on GitHub](https://github.com/code-corps/code-corps-api).

This document outlines how to interact with the API's resource-oriented URLs. JSON API errors returned by the API are also documented along with their HTTP status codes.

This API is intended for direct consumption by the Code Corps Ember application.

The production API can be found at `https://api.codecorps.org`.

The staging API can be found at `https://api.pbqrpbecf.org`.

The remote development API can be found at `https://api.pbqrpbecf-qri.org`.

# Authentication
When using the API's authenticated endpoints you can authenticate users by exchanging the `username` and `password` for an OAuth token.

## OAuth Token Exchange [/oauth/token]
Exchange credentials for `access_token`.

### Exchange credentials for token [POST]
+ Request
    + Attributes (OAuth Grant Request)
    + Headers

            Authorization: Basic 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
            Content-Type: application/x-www-form-urlencoded

+ Response 200 (application/json)
    + Attributes (OAuth Valid Response)

+ Response 401 (application/json)
    + Attributes (OAuth Invalid Response)

# Group Categories

## Category [/categories/new]

### Create a category [POST]

+ Request
  + Attributes (OAuth Grant Request)

+ Headers

  Authorization: Basic 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8

+ Response 201 (application/vnd.api+json)

  + Attributes (Category Response)

+ Response 422 (application/vnd.api+json)

  + Attributes (Unprocessable Entity Response)

## Category [/categories/{id}]

### Retrieve a category [GET]

+ Request
  + Attributes (OAuth Grant Request)

+ Headers

  Authorization: Basic 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8

+ Response 200 (application/vnd.api+json)

  + Attributes (Category Response)

+ Response 404 (application/vnd.api+json)

  + Attributes (Record Not Found Response)

## Category [/categories/{id}/edit]

### Update a category [PUT]

+ Request
  + Attributes (OAuth Grant Request)

+ Headers

  Authorization: Basic 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8

+ Response 204 (application/vnd.api+json)

  + Attributes (No Content Response)

+ Response 404 (application/vnd.api+json)

  + Attributes (Record Not Found Response)

+ Response 409 (application/vnd.api+json)

  + Attributes (Creation Conflict Response)

## Categories [/categories]

### List all categories [GET]

+ Request
  + Attributes (OAuth Grant Request)

+ Headers

  Authorization: Basic 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8

+ Response 200 (application/vnd.api+json)

  + Attributes (Categories Response)

# Group Comment Images

## Comment Image [/comment_images]

### Create a Comment Image [POST]

+ Request
  + Attributes (OAuth Grant Request)

+ Headers

  Authorization: Bearer 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8

+ Response 201 (application/vnd.api+json)

  + Attributes (Comment Image Response)

+ Response 422 (application/vnd.api+json)

  + Attributes (Unprocessable Entity Response)

# Group Comment User Mentions

# Group Comments

# Group Github Repositories

# Group Import Skill Failures

# Group Imports

# Group OAuth Applications

# Group Organization Memberships

# Group Organizations

# Group Ping

# Group Post Images

# Group Post Likes

# Group Post User Mentions

# Group Posts

# Group Preview User Mentions

# Group Previews

## Preview [/previews]

### Create a preview [POST]

+ Request

  + Attributes (OAuth Grant Request)

+ Headers

  Authorization: Bearer {access_token}

+ Response 201 (application/vnd.api+json)

  + Attributes (Preview Response)

+ Response 401 (application/json)

  + Attributes (OAuth Invalid Response)

+ Response 422 (application/vnd.api+json)

  + Attributes (Unprocessable Entity Response)

# Group Project Categories

# Group Project Roles

# Group Projects

# Group Roles

# Group Role Skills

This group is used as a join table to connect the many to many relationship of Skills and Roles

This allows A Skill to be under different Roles and a Role to have multiple Skills

## Role Skill [/role_skills]

### Create a Role Skill [POST]

+ Request

  + Attributes (OAuth Grant Request)

+ Headers

  Authorization: Bearer {access_token}

+ Response 200 (application/vnd.api+json)

  + Attributes (Role Skill Response)

+ Response 401 (application/json)

  + Attributes (OAuth Invalid Response)

+ Response 403 (application/json)

  + Attributes (Forbidden Response)

+ Response 422 (application/vnd.api+json)

  + Attributes (Unprocessable Entity Response)

# Group Skills

# Group Slugged Routes

# Group User Categories

# Group User Roles

# Group User Skills

# Group Users

## Users [/users]

### Create a user [POST]

+ Request (application/vnd.api+json)

    + Headers

        Accept: application/vnd.api+json

    + Attributes (object)

        + data (object)
            + type: `users` (string, required)
            + attributes (object)
                + base64_photo_data: `data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7` (string, optional)
                + email: `me@testuser.org` (string, optional)
                + facebook_id: `1234567890` (string, optional)
                + facebook_access_token: `CAABwiWr8tH8BAGKCYOIgoMwJ9T0ZAmJ6KJJNcUjzmftdAOCx1RgzxZAjzGB1s37DDCEoy9r2VgrCLffCTvEGe9cZBZPAwBhygi2ZpTubZC2eCzMe16CLP4Wlc9bStWGwUNYoLEl4dXu4uJl2CCLiFXEtP4GKDv0Gk4s35iXty77KZBx5NYBCcEUs98WjdJQcXLsb1X2ZBaMTW2AZDZN` (string, optional)
                + password: `password` (string, required)
                + username: `testuser` (string, required)

+ Response 201 (application/vnd.api+json)

    + Attributes (User Response)

+ Response 422 (application/vnd.api+json)

    + Attributes (Unprocessable Entity Response)

### Find a user [GET /users/{id}]

+ Parameters

    + id - The Id of a user.

+ Request

    + Headers

        Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Attributes (User Response)

+ Response 404 (application/vnd.api+json)

    + Attributes (Record Not Found Response)

### Check email availability [GET /users/email_available?email={email}]

+ Parameters

    + email: me@testuser.org (string, required)

+ Response 200 (application/vnd.api+json)

    + Attributes

        + available: `true` (boolean)
        + valid: `true` (boolean)

### Check username availability [GET /users/username_available?username={username}]

+ Parameters

    + username: testuser (string, required)

+ Response 200 (application/vnd.api+json)

    + Attributes

        + available: `true` (boolean)
        + valid: `true` (boolean)

### Update a user [PATCH /users/{id}]

+ Parameters

    + id: `1` - The Id of a user.

+ Request (application/vnd.api+json)

    + Attributes
        + data
            + Include (User Resource Identifier)
            + attributes (object)
                + first_name: `Test` (string, optional)
                + last_name: `User` (string, optional)
                + website: `https://testuser.org` (string, optional)
                + biography: `Sample bio.` (string, optional)
                + twitter: `testuser` (string, optional)
                + base64_photo_data: `data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7` (string, optional)
                + `state_transition`: `signed_up` (string, optional)
                + theme: `light` (string, optional)

    + Headers

        Authorization: Bearer {access_token}
        Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Attributes (User Response)

+ Response 401 (application/vnd.api+json)

    + Attributes (OAuth Invalid Response)

+ Response 403 (application/vnd.api+json)

    + Attributes (Forbidden Response)

+ Response 422 (application/vnd.api+json)

    + Attributes (Unprocessable Entity Response)

### Update me [PATCH /users/me]

+ Request (application/vnd.api+json)

    + Attributes
        + data
            + Include (User Resource Identifier)
            + attributes (object)
                + first_name: `Test` (string, optional)
                + last_name: `User` (string, optional)
                + website: `https://testuser.org` (string, optional)
                + biography: `Sample bio.` (string, optional)
                + twitter: `testuser` (string, optional)
                + base64_photo_data: `data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7` (string, optional)
                + `state_transition`: `signed_up` (string, optional)
                + theme: `light` (string, optional)

    + Headers

        Authorization: Bearer {access_token}
        Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Attributes (User Response)

+ Response 401 (application/vnd.api+json)

    + Attributes (OAuth Invalid Response)

+ Response 422 (application/vnd.api+json)

    + Attributes (Unprocessable Entity Response)

### List users [GET /users?filter[id]={ids}]

+ Parameters

    + `filter[id]`: `1,2` (required, string)

+ Request (application/vnd.api+json)

+ Response 200 (application/vnd.api+json)

    + Attributes (Users Response)

+ Response 404 (application/vnd.api+json)

    + Attributes (Record Not Found Response)

## User [/user]

### Show authenticated user [GET]

+ Request (application/vnd.api+json)

    + Headers

        Authorization: Bearer {access_token}
        Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Attributes (User Response)

+ Response 401 (application/vnd.api+json)

    + Attributes (OAuth Invalid Response)

# Data Structures

## Category (object)
+ name: `Category` (required, string)
+ slug: `cat1` (required, string)
+ description: `This is the category description` (string)

## Categories Relationship (object)
+ data
  + id: 1 (string)
  + type: categories (string)

## Categories Relationships (object)
+ categories
  + data(array[Categories Relationship], required)

## Category Relationships Base (object)
+ include Project Categories Relationship

## Category Resource Identifier
+ id: `1` (string)
+ type: `categories`

## Category Response (object)
+ data
  + id: `1` (string)
  + type: `categories` (string)
  + attributes(Category, required)
  + relationships(Category Relationships Base, required)

## Categories Response (object)
+ categories
  + data(array[Category], required)

## Comment Image (object)
+ filename: `file name` (string)

## Comment Image Relationships Base (object)
+ comment
  + data(Comments Relationship)
+ user
  + data(User Resource Identifier)

## Comment Image Response Base (object)
+ id: `1` (string)
+ type: `comment_images` (string)
+ attributes(Comment Image)
+ relationships(Comment Image Relationships Base)

## Comment Image Response (object)
+ data(Comment Image Response Base)

## Comments Relationship (object)
+ id: 1 (string)
+ type: comments (string)

## Creation Conflict Response (object)
+ title: `Conflict` (string)

+ detail: `{Object} with 'id'={id} already created` (string) - Details of what record was already there.

+ status: 409 (number) - HTTP status code

## Forbidden Response (object)
+ errors (array)
    + Attributes
        + id: `FORBIDDEN` (string)
        + title: `Forbidden` (string)
        + detail: `You are not authorized to perform this action on {subject_name}` (string) - Details of what record was not found.
        + status: 403 (number) - HTTP status code

## No Content Response (object)

+ title: `No Content` (string)

+ status: 204 (number) - HTTP status code

## OAuth Grant Request (object)
  + grant_type: `password` (string, required)
  + username: `me@testuser.org` (string, required) - The user's email address.
  + password: `password` (string, required)

## OAuth Invalid Response (object)
+ errors (array)
    + Attributes
        + id: `INVALID_GRANT` (string, required)
        + title: `Invalid grant` (string, required)
        + detail: `The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.` (string, required)
        + status: 401 (number, required)

## OAuth Valid Response (object)
+ access_token: `5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8` (string, required)
+ token_type: `bearer` (string, required)
+ expires_in: 7200 (number, required)
+ refresh_token: `f160d958cab936626305062dc594c2cadb12712ebc7cbca091a27ec4921b91d8` (string, required)
+ created_at: 1468283904 (number, required)
+ user_id: 1 (number, required)

## Organization Membership Resource Identifier
+ id: `1` (string)
+ type: `organization_memberships` (string)

## Organization Resource Identifier
+ id: `1` (string)
+ type: `organizations` (string)

## Preview (object)
+ body: `<p>A <strong>strong</strong> preview</p>` (string)
+ markdown: `A *strong* preview` (string)

## Preview Response Base (object)
+ id: `1` (string)
+ type: `previews` (string)
+ attributes(Preview, required)
+ relationships(Preview Relationships Base, required)

## Preview Response (object)
+ data(Preview Response Base)

## Previews Relationship (object)
+ id: 1 (string)
+ type: previews (string)

## Preview Relationships Base (object)
+ include User Resource Identifier
+ include Preview User Mentions Relationship

## Preview User Mentions Relationship (object)
+ id: 1 (string)
+ type: preview_user_mentions (string)

## Project Categories Relationship (object)
+ id: 1 (string)
+ type: project_categories (string)

## Record Not Found Response (object)
+ errors (array)
    + Attributes
        + id: `RECORD_NOT_FOUND` (string)
        + title: `Record not found` (string)
        + detail: `Couldn't find {object} with 'id'={id}` (string) - Details of what record was not found.
        + status: 404 (number) - HTTP status code

## Role Resource Identifier
+ id: `1` (string)
+ type: `roles` (string)

## Skill Resource Identifier
+ id: `1` (string)
+ type: `skills` (string)

## Role Skill Response (object)
+ data(Role Skill Resource)

## Role Skill Resource (object)
+ include Role Skill Resource Identifier
+ relationships
  + roles
    + data(array[Role Resource Identifier])
    + data(array[Skill Resource Identifier])
    + links

## Role Skill Resource Identifier (object)
+ id: 1 (string)
+ type: role_skills (string)

## Unprocessable Entity Response (object)
+ errors (array)
    + Attributes
        + title: `Unprocessable Entity` (string)
        + status: 422 (number) - HTTP status code

## User Attributes (object)
+ created_at: `2016-07-08T03:03:51.967Z` (string)
+ email: `me@testuser.org` (string)
+ first_name: `Test` (string)
+ last_name: `User` (string)
+ name: `Test User` (string)
+ username: `testuser` (string)
+ twitter: `testuser` (string)
+ biography: `Sample bio.` (string)
+ website: `https://testuser.org` (string)
+ facebook_id: `1234567890` (string)
+ facebook_access_token: `CAABwiWr8tH8BAGKCYOIgoMwJ9T0ZAmJ6KJJNcUjzmftdAOCx1RgzxZAjzGB1s37DDCEoy9r2VgrCLffCTvEGe9cZBZPAwBhygi2ZpTubZC2eCzMe16CLP4Wlc9bStWGwUNYoLEl4dXu4uJl2CCLiFXEtP4GKDv0Gk4s35iXty77KZBx5NYBCcEUs98WjdJQcXLsb1X2ZBaMTW2AZDZN` (string)
+ photo_thumb_url: `https://d3pgew4wbk2vb1.cloudfront.net/icons/user_default_thumb.png` (string)
+ photo_large_url: `https://d3pgew4wbk2vb1.cloudfront.net/icons/user_default_large.png` (string)
+ state: `signed_up` (string)
+ theme: `light` (string)

## User Relationships (object)
+ categories (object)
  + data(array[Category Resource Identifier])
+ organization_memberships (object)
  + data(array[Organization Membership Resource Identifier])
+ organizations (object)
  + data(array[Organization Resource Identifier])
+ roles (object)
  + data(array[Role Resource Identifier])
+ skills (object)
  + data(array[Skill Resource Identifier])
+ user_categories (object)
  + data(array[User Category Resource Identifier])
+ user_roles (object)
  + data(array[User Role Resource Identifier])
+ user_skills (object)
  + data(array[User Skill Resource Identifier])

## User Response (object)
+ data (object)
    + Include (User Resource)
    + relationships
        + Include (User Relationships)

## Users Response (object)
+ data(array[User Resource])

## User Resource (object)
+ Include User Resource Identifier
+ attributes (User Attributes)

## User Resource Identifier (object)
+ id: `1` (string)
+ type: `users` (string)

## User Category Resource Identifier
+ id: `1` (string)
+ type: `user_categories` (string)

## User Role Resource Identifier
+ id: `1` (string)
+ type: `user_roles` (string)

## User Skill Resource Identifier (object)
+ id: `1` (string)
+ type: `user_skills` (string)
